### ISSUE TITLE
Wrong path suggested for Indigo 2021.1

### ISSUE THREAD

**Issue by FlyingDiver** [DaveL17/matplotlib#3]
Just installed 2021.1 and got the following messages.
```
   Matplotlib Error                Charts are being saved to: /Library/Application Support/Perceptive Automation/Indigo 7.5/Charts/)
   Matplotlib Error                You may want to change the save path to: /Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoWebServer/images/controls/static/
```
`IndigoWebServer` is now `Web Assets`

**Comment by DaveL17** [comment]
Thanks Joe -- appreciate the head's up. Will gin up a conditional message depending on what version a user is coming from (as now there's at least two possible locations to contend with).
